pull_request_rules:
  - name: Automatic merges for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build
      - check-success=unitTests
      - check-success=staticAnalysis
      - check-success=danger
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash

  - name: Be author's friend
    conditions:
      - author~=^CharlesMoreira1
      - check-success=build
      - check-success=unitTests
      - check-success=staticAnalysis
      - check-success=danger
    actions:
      merge:
        method: squash