name: Publish Debug APK CD

on:
  push:
    tags:
      - v*

jobs:
  uploadRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Setup checkout
        uses: actions/checkout@v2

      - name: Build debug apk
        run: ./gradlew clean assembleDebug

      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/zip